"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type ResumeRow = { id: string; fileName: string; status: string; createdAt: string; extraction: null | { name: string | null; email: string | null; phone: string | null; designation: string | null; overallConfidence: number } };
export default function ResumeList({ title, status }: { title: string; status?: string }) {
  const [items, setItems] = useState<ResumeRow[]>([]); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [pages, setPages] = useState(1);
  useEffect(() => { const params = new URLSearchParams({ page: String(page), limit: "25" }); if (status) params.set("status", status); if (search) params.set("search", search); void fetch(`/api/resumes?${params}`).then((response) => response.ok ? response.json() : null).then((data) => { if (data) { setItems(data.items); setTotal(data.total); setPages(data.pages || 1); } }); }, [page, search, status]);
  return <main className="tool-page"><div className="tool-header"><div><Link href="/" className="back-link">← Workspace</Link><h1>{title}</h1><p>{total.toLocaleString()} resumes in this view</p></div><Link className="button button-primary" href="/import">＋ Import resumes</Link></div><section className="panel table-panel"><div className="table-toolbar"><label className="search-box"><span>⌕</span><input placeholder="Search by name, email or file…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></label><Link href="/export" className="filter-button">⇩ Export</Link></div><div className="table-scroll"><table><thead><tr><th>FILE / CANDIDATE</th><th>EMAIL</th><th>PHONE</th><th>DESIGNATION</th><th>CONFIDENCE</th><th>STATUS</th><th>CREATED</th></tr></thead><tbody>{items.map((row) => <tr key={row.id}><td><Link className="candidate-cell" href={`/resumes/${row.id}`}><span className="candidate-avatar tone-violet">{(row.extraction?.name ?? "CV").slice(0, 2).toUpperCase()}</span><div><b>{row.extraction?.name ?? "Needs review"}</b><span>{row.fileName}</span></div></Link></td><td>{row.extraction?.email ?? "—"}</td><td>{row.extraction?.phone ?? "—"}</td><td>{row.extraction?.designation ?? "—"}</td><td>{Math.round((row.extraction?.overallConfidence ?? 0) * 100)}%</td><td><span className={`status-pill ${row.status === "COMPLETED" ? "status-complete" : "status-review"}`}>{row.status}</span></td><td>{new Date(row.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{items.length === 0 && <div className="empty-search">No resumes found.</div>}</div><div className="table-footer"><span>Page {page} of {pages}</span><div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>←</button><button disabled={page >= pages} onClick={() => setPage(page + 1)}>→</button></div></div></section></main>;
}
