"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Batch = { id: string; name: string; status: string; totalFiles: number; processedFiles: number; createdAt: string };
export default function BatchesPage() {
  const [items, setItems] = useState<Batch[]>([]); const [message, setMessage] = useState("");
  async function reload() { const response = await fetch("/api/batches"); if (response.ok) setItems((await response.json()).items); }
  useEffect(() => { const timeout = window.setTimeout(() => void reload(), 0); const interval = window.setInterval(() => void reload(), 8000); return () => { window.clearTimeout(timeout); window.clearInterval(interval); }; }, []);
  async function control(action: string) { const response = await fetch(`/api/processing/${action}`, { method: "POST" }); setMessage(response.ok ? `Processing ${action === "start" ? "started" : action === "pause" ? "paused" : "resumed"}.` : "Processing control failed."); await reload(); }
  return <main className="tool-page"><div className="tool-header"><div><Link href="/" className="back-link">← Workspace</Link><h1>Processing batches</h1><p>Queue status updates automatically.</p></div><div className="batch-controls"><button className="button button-secondary" onClick={() => void control("pause")}>Pause</button><button className="button button-primary" onClick={() => void control("start")}>Start processing</button><button className="button button-secondary" onClick={() => void control("resume")}>Resume</button></div></div>{message && <p>{message}</p>}<section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>BATCH</th><th>STATUS</th><th>PROGRESS</th><th>CREATED</th><th /></tr></thead><tbody>{items.map((batch) => <tr key={batch.id}><td><b>{batch.name}</b></td><td>{batch.status}</td><td>{batch.processedFiles.toLocaleString()} / {batch.totalFiles.toLocaleString()}</td><td>{new Date(batch.createdAt).toLocaleString()}</td><td>{!["COMPLETED", "CANCELLED"].includes(batch.status) && <button className="clear-button" onClick={async () => { const response = await fetch(`/api/batches/${batch.id}/cancel`, { method: "POST" }); setMessage(response.ok ? "Batch cancelled. Active resumes will finish." : "Could not cancel this batch."); await reload(); }}>Cancel</button>}</td></tr>)}</tbody></table>{items.length === 0 && <div className="empty-search">No batches uploaded yet.</div>}</div></section></main>;
}
