"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type ResumeDetail = { fileName: string; status: string; fileType: string; extraction?: { name?: string | null; email?: string | null; phone?: string | null; designation?: string | null; overallConfidence?: number } | null };
export default function ResumeDetail({ params }: PageProps<"/resumes/[id]">) {
  const [id, setId] = useState(""); const [record, setRecord] = useState<ResumeDetail | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { void params.then(({ id: resumeId }) => { setId(resumeId); void fetch(`/api/resumes/${resumeId}`).then((response) => response.ok ? response.json() as Promise<ResumeDetail | null> : null).then(setRecord); }); }, [params]);
  async function save(form: FormData) { const response = await fetch(`/api/resumes/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name") || null, email: form.get("email") || null, phone: form.get("phone") || null, designation: form.get("designation") || null }) }); setMessage(response.ok ? "Review saved." : "Could not save review."); }
  if (!record) return <main className="tool-page">Loading resume…</main>;
  const extraction = record.extraction ?? {};
  return <main className="tool-page"><div className="tool-header"><div><Link href="/resumes" className="back-link">← All resumes</Link><h1>Review resume</h1><p>{record.fileName} · {record.status}</p></div></div><section className="tool-panel review-layout"><div><h2>Original resume</h2><p>Private file · {record.fileType.toUpperCase()}</p><a className="button button-secondary" href={`/api/resumes/${id}/file`}>Open resume</a></div><form action={save} className="review-form"><h2>Extracted candidate data</h2><label>Name<input className="tool-input" name="name" defaultValue={extraction.name ?? ""} /></label><label>Email<input className="tool-input" name="email" defaultValue={extraction.email ?? ""} /></label><label>Phone<input className="tool-input" name="phone" defaultValue={extraction.phone ?? ""} /></label><label>Designation<input className="tool-input" name="designation" defaultValue={extraction.designation ?? ""} /></label><p>Confidence: {Math.round((extraction.overallConfidence ?? 0) * 100)}%</p>{message && <p>{message}</p>}<button className="button button-primary">Save review</button></form></section></main>;
}
